services:
  eva-forward:
    build: .
    environment:
      ADMINS: $ADMINS
      API_ID: $API_ID
      API_HASH: $API_HASH
      BOT_TOKEN: $BOT_TOKEN     
      TARGET_CHANNEL: $TARGET_CHANNEL
     
    
